### PR TITLE
configure.ac: include libnetwork for haiku support

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by jessicah** [comment]
Will probably also need backporting.

**Comment by andreasabel** [comment]
> Will probably also need backporting.

@jessicah Thanks for the PR.  What should this change be backported to?

**Comment by jessicah** [comment]
I'm pretty sure I've seen 0.1.2.0 selected by cabal in a couple of instances instead of 2.0.1 whilst building various libraries.

**Comment by andreasabel** [comment]
> I'm pretty sure I've seen 0.1.2.0 selected by cabal in a couple of instances instead of 2.0.1 whilst building various libraries.

NB: 2.0.1 -> 0.2.0.1
Ah I see what you mean.  In most cases, older major versions are not maintained, so without special requests we wouldn't do it here either.  Users should add lower bound `resolv >= 0.2` to their `build-depends` if they want to utilize this fix, this would be default procedure.

**Comment by andreasabel** [comment]
@lyokha : Shall we release this as 0.2.0.2?  I checked it locally on macOS.  
I don't remember: is Windows supported at all?  If yes, we should add some CI for it.

**Comment by lyokha** [comment]
@andreasabel, I would even release this as `0.2.1.0` as adding support for a new OS is a fair new feature. But I have a question to @jessicah. I'm not familiar with Haiku but its docs say that *libnetwork* is combined from *libsocket* and *libbind*. Supposedly, libbind is what really needed for resolv, but it's already checked by configure. So, the question is: do we really need adding *libnetwork* to configure when we already check *libbind*?

**Comment by jessicah** [comment]
@lyokha ah, the wording is a bit weird there. `libnetwork` is the equivalent of those two libraries on Haiku. Haiku doesn't have `libsocket` or `libbind`.

**Comment by lyokha** [comment]
@jessicah, thank you for clarifying this! @andreasabel, regarding Windows, I don't know if it's supported.

**Comment by andreasabel** [comment]
I _think_ Haskell PVP would allow a patch release (0.2.0.2) here since the API did not change, we merely fixed a problem.
Or is it that this change could make installation fail where it succeeded before?  Then we would need a major bump to 0.3.

**Comment by jessicah** [comment]
No, I don't believe it would cause a failure from a previous success, as libnetwork would be a) tested last, and b) only succeed if it contained that symbol. And similar patches to configure scripts have been upstreamed for years now ;-)

**Comment by lyokha** [comment]
I'm not sure what version this should be, *0.2.0.2* seems also good.

**Comment by andreasabel** [comment]
I tried installation on windows; it fails with `configure: error: required <resolv.h> header not found`.  So I guess we do not have to worry about Windows.

**Comment by andreasabel** [comment]
Release candidate: https://hackage.haskell.org/package/resolv-0.2.0.2/candidate

**Comment by lyokha** [comment]
@andreasabel, do not forget to `autoreconf - i` in the working directory to generate a proper configure before making a dist

**Comment by andreasabel** [comment]
Ok, published as 0.2.0.2!

**Pull request merged**
