### PR TITLE
Changelog v0.2.0.0

### PR DESCRIPTION
**Pull request by lyokha**
Andreas: Candidate at: https://hackage.haskell.org/package/resolv-0.2.0.0/candidate

### CODE REVIEW

**Comment by lyokha** [comment]
Version in *resolv.cabal* must be also bumped to `0.2.0.0`. @andreasabel, what is your opinion: should this be made in this PR or in a separate task?

**Comment by andreasabel** [comment]
> Version in _resolv.cabal_ must be also bumped to `0.2.0.0`

I did this on `master` now since we already decided to release the next version as `0.2.0.0` (and we have added `@since` info to the other PR).  Usually, I might do this in the PR that prepares the release.

The changelog you wrote is good!
I just added links to the PRs so one can quickly get more information.
Also, I added release dates and author to the previous releases (on `master`).

Once everything is ready for release, the release date has to be inserted here.
After releasing and merging this, we also need to set the `v0.2.0.0` tag on this repo.

**Comment by lyokha** [comment]
I added yet another tiny improvement to #17 (https://github.com/haskell-hvr/resolv/pull/17/commits/de12926d5564e21e05cc2707fd117256bc3a320f), seems that you didn't merge this yet.

**Comment by andreasabel** [comment]
> I added yet another tiny improvement to #17

Me too, please review!

**Comment by andreasabel** [comment]
Candidate looks fine: https://hackage.haskell.org/package/resolv-0.2.0.0/candidate

Shall I release?

**Comment by lyokha** [comment]
Yes, I think it's ok to release!

**Comment by andreasabel** [comment]
Done!  Thanks for the nice collaboration!

**Pull request merged**
